### ISSUE TITLE
Introduce missing Entity-bound operations on ElasticsearchTemplate [DATAES-686]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1259]
**[jvmlet](https://jira.spring.io/secure/ViewProfile.jspa?name=jvmlet)** opened **[DATAES-686](https://jira.spring.io/browse/DATAES-686?redirect=false)** and commented

Please make all auxiliary methods in  **AbstractElasticsearchRepository** as **protected** to make implementation of custom base repository easier, taking advantage of all methods implementation from AbstractElasticsearchRepository , like  _createIndexQuery_ .

Also, _save/indexAllWithoutRefresh_ method is missing from _ElasticsearchRepository_  interface

---

**Affects:** 3.2.1 (Moore SR1)

**Comment by sothawo** [comment]
entity bound operations are introduced since 4.0. About opening mehtods from `AbstractElasticsearchClient`: This class is not meant as a bas class to be used externally. It combines the common things for both the `ElasticsearchTemplate` and the `ElasticsearchRestTemplate`. When the transport client is removed from Elasticsearch, the `ElasticsearchTemplate` will be removed as well and there will be no reason for the `AbstractElasticsearchClient` to exist anymore, there will  only be the `ElasticsearchRestTemplate` then.

Waiting for feedback on this issue, otherwise it will be automatically be closed.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
