### ISSUE TITLE
Implement support for reindex API [DATAES-955]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1529]
**[sothawo](https://jira.spring.io/secure/ViewProfile.jspa?name=sothawo)** opened **[DATAES-955](https://jira.spring.io/browse/DATAES-955?redirect=false)** and commented

`IndexOperations` should support the reindex API, see linked reference

---

**Reference URL:** https://www.elastic.co/guide/en/elasticsearch/reference/7.9/docs-reindex.html

**Comment by oni7uka** [comment]
I am using reindex api, I can send pull request to implement this enhancement, the implementation is similar to [putTemplate](https://github.com/spring-projects/spring-data-elasticsearch/blob/056a4a76e7e0dc9f09b6c3657bb081a27e456f78/src/main/java/org/springframework/data/elasticsearch/core/IndexOperations.java#L228), but I have some confusion, reindex and putTemplate are not dependent on a specific index, but the implementation of IndexOperations is RestIndexTemplate which constructor must specify IndexCoordinates or boundClass, It doesn't make sense

**Comment by sothawo** [comment]
####about `putTemplate`

Elasticsearch has this under [Index APIs](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/indices.html) that's the reason why it is in the `IndexOperations` interface. I agree that it makes no sense to have to get an `IndexOperations` by providing an indexname or class when it is not needed. 

We could introduce something like

````java
public class IndexCoordinates {

	public static final IndexCoordinates UNSPECIFIED = IndexCoordinates.of("UNSPECIFIED");
  
	// ...
}
````

in order to be able to obtain an `IndexCoordinates` without specifying an index. Using the capitals in the name ensures that this cannot be used in a request that needs an index name.

#### about `reindex`

Elasticsearch lists this under [Document APIs](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-reindex.html), so it should go as a method into `DocumentOperations` and as thus should be implemented in the `ElasticsearchTemplate` classes. If you want to implement this: we need it in imperative and in reactive code, tests would probably 
be integration tests with indexing into one index, then reindex and then read from the second one.

If you wanna do that, give me short notice, I'll mark the issue then as being worked on (although the number of people working on issues is low, almost only me ;-) )

**Comment by oni7uka** [comment]
Reindex does need to be implemented in DocumentOperations so it seems reasonable. And yes, I will implement this.
