### ISSUE TITLE
Add rescore functionality to NativeSearchQuery

### ISSUE THREAD

**Issue by peermuellerxw** [spring-projects/spring-data-elasticsearch#1686]
Hi, wanted to ask if there is any reason why the [rescore](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-rescore.html) functionality is not implemented for NativeSearchQuery? Would you like a PR?

**Comment by sothawo** [comment]
Probably because it never was requested as a feature.

If you want to implement it, take care that this must beimplemented in all the clients/operations (transport, rest, reactive).

It probably makes sense to add the possibility for adding rescore queries to all `Query` implementations, not only `NativeSearchQuery`

**Comment by peermuellerxw** [comment]
Hi @sothawo,
thanks for your quick reply. However, I do not really understand your concerns. As far as I understand the type of query and the client that is used for the connection do not affect each other. Meaning, that the NativeSearchQuery can be used for transport/rest/reactive clients...

I opened a PR. Reviews are welcome.

Could also add a rescorer annotation if wanted...
