### ISSUE TITLE
How to remove the _class field when automatically creating index and how to specify what fields we want return in query?

### ISSUE THREAD

**Issue by fengnex** [spring-projects/spring-data-elasticsearch#1883]
There are two questions:
1. A field named _class will be inserted automatically when spring-data-elasticsearch creates an index, even though it is not desired. I wonder how to avoid that.
2.  *Repository always return ALL fields from elasticsearch after querying, and how to specify the fields we want to return? Not ALL.

**Comment by sothawo** [comment]
> 1. A field named _class will be inserted automatically when spring-data-elasticsearch creates an index, even though it is not desired. I wonder how to avoid that.

Implemented with #1788, this is contained since release 4.3.0-M1, check [the documentation](https://docs.spring.io/spring-data/elasticsearch/docs/4.3.0-M1/reference/html/#elasticsearch.mapping.meta-model.rules) for details (last part of the linked chapter).

>2. Repository always return ALL fields from elasticsearch after querying, and how to specify the fields we want to return? Not ALL.

Currently not possible with repository methods, only when you use an `ElasticsearchOperations` implementation when sednding a query. The `Query` has `setFields()` or `addSourceFilter()` for this purpose.

**Comment by fengnex** [comment]
@sothawo Thank you and I found that _class seems necessary and it is recommended not to disable it.

**Comment by sothawo** [comment]
Do you use the current milestone version for 4.3 (4.3.0-M1)? If you get this compiler version you are using one of the released versions.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
