### ISSUE TITLE
Field annotation behavior

### ISSUE THREAD

**Issue by schikin** [spring-projects/spring-data-elasticsearch#1912]
It seems like there is a bug with "@Field" annotation auto-mapping, the following document class (Kotlin):

```
@Document(indexName = "jobs")
data class JobIndex(
    @Id
    val jobId: UUID,

    @Field(type= FieldType.Nested)
    val tags: List<Tag> = emptyList(),

    @Field
    val startedAt: Date,

    @Field
    val finishedAt: Date? = null,

    @Field
    val type: String,

    @Field
    val state: JobState
)
```

Creates the following mapping:

```
{
  "mapping": {
    "properties": {
      "_class": {
        "type": "keyword",
        "index": false,
        "doc_values": false
      },
      "tags": {
        "type": "nested",
        "properties": {
          "_class": {
            "type": "keyword",
            "index": false,
            "doc_values": false
          }
        }
      }
    }
  }
}
```

All the fields besides a nested one are missing from the mapping

Using ver. 4.2.4

**Comment by sothawo** [comment]
The default value for the `type` attribute of the `@Field` annotation is `FieldType.Auto`. Which means that Spring Data Elasticsearch does not write a mapping for the property but Elasticsearch will try to guess the type when the first document is indexed.

How should Spring Data Elasticsearch map these properties? A `String` for example  could be _text_ or _keyword_. So you need to provide the type/mapping that the property if you do not want to have the auto mapping.

And please, do not you `Date`, but one of the temporal classes from the `java.time` package, available since Java 8.

**Comment by schikin** [comment]
Ah ok, so in order to have mappings defined upon deployment, I need to manually specify the mapping type. 

I guess it needs to be documented somewhere as my understanding of FieldType.Auto would be that data-es would try to infer mapping type based on a data type (`text` for `String` , `float` for decimals, etc). 

The fact that it relies on ES to index a document is probably justified (it's much easier to do) but leads to weird behaviour when everything works most of the time, i.e:
- In an existing system where documents already exist
- In case of new indices when you only try to query the data after it has been populated (which is most cases)
But that throws an exception if you, for example, try to query findByOrderBy<field> on an empty index

I am closing this

**Comment by sothawo** [comment]
This was added to the documentation in 4.3.0-M1.
