### ISSUE TITLE
Support for separate annotation for transient fields (Alias for @Transient)

### ISSUE THREAD

**Issue by AntonLGVS** [spring-projects/spring-data-elasticsearch#1990]
I am faced with a problem when one and the same entity is used for JPA and for ElasticSearch. These entities have different fields to save.
Exemple:
```java
@Entity // JPA annotation
@Document // ES annotation
public class entity {
    @Column
    @Field
    private String field1;

     @Column
     @DropField // new annotation
     private String veryBigText;

     ...........and many other fields
}
```

Thus, field veryBigText will get into the database, but will not get into the ElasticSearch index. I have an idea how to implement this. I want to know the demand for this functionality. 
What do you think about this?

**Comment by sothawo** [comment]
If we would add an additional annotation, it should be named something like `@ElasticsearchTransient`; it would not be an alias to `@Transient`, more an alternative that is only evaluated in Spring Data Elasticsearch and not in other Spring Data stores.

Basically I always discourage from using the same entity for different stores because this leads to problems like this.

About demand for this functionality: I think I had one or two questions about transient properties in the last years either as issues or on StackOverflow. I don't know if this is an issue in other stores. 

@mp911de do you know if there are this kind of store-specialized annotations in other stores? What do you think of this?

**Comment by mp911de** [comment]
That doesn't make any sense as we would end up with `@MongoTransient`, `@RedisTransient`, `@…Transient` across the board and that isn't helpful. Please either use two different domain models or use entity callbacks to filter the properties to remove after the mapping process.

The code above is a typical example where you want to represent two things with a single Java class and where reuse creates more trouble than benefit and we generally aim for clear and conciseness instead of supporting confusing data models.

**Comment by AntonLGVS** [comment]
Thanks for your clarification. this will indeed spawn a lot of annotations. I think the question is closed.
