### ISSUE TITLE
How about replacing java.lang.reflect call with org.springframework.util.ReflectionUtils

### ISSUE THREAD

**Issue by AntonLGVS** [spring-projects/spring-data-elasticsearch#2027]
What do you think about making this replacement?
 **ReflectionUtils** has a cache that allows you to reduce call to the Java Security Manager (Deprecated in Java 17).
As I understand it, this may allow better optimization for the Spring Native (and other Cloud Nantive).
And  java.lang.reflect calls is low-level API. 

Current classes having calls to  java.lang.reflect:
1. MappingElasticsearchConverter#populateScriptFields
2. IndexBuilder#buildIndex

**Comment by sothawo** [comment]
ad 1: This should be improved:  here a `ElasticsearchPersistentEntity` should be used to get the properties which are annotated with `ScriptedField` because in Spring Data Elasticsearch this is where all the reflective access to the entity should be implemented (this class is using the Spring methods for reflection). For writing to the field the `ElasticsearchPersisntentProperty` for that field should be used. 

ad 2: this is an old (ugly) implementation to index an object and is only used in test scope. This could be refactored to something that does not use the reflection. But this is not relevant to native code, as it's only in the test

**Comment by AntonLGVS** [comment]
Case 2: I don't know how you can do something with an entity without using reflaction. And you also said that in makes no sense because it is in the test scope.
