### ISSUE TITLE
Use ElasticsearchDateConverter  format same time, but get different timezone result

### ISSUE THREAD

**Issue by wd0401** [spring-projects/spring-data-elasticsearch#2050]
if now date is : 2022-01-06 16:43:09 , but I get two different results and two different time zone, is this a issue? 

I use the follow codes: 
`
 public static void main(String[] args) {
        ElasticsearchDateConverter elasticsearchDateConverter = ElasticsearchDateConverter.of("yyyy-MM-dd HH:mm:ss");
        // 1
        LocalDateTime localDateTime = LocalDateTime.now();
        Date date = new Date();
        // 2
        String localStr = elasticsearchDateConverter.format(localDateTime);
        System.out.println(localStr); //2022-01-06 16:43:09

        // 3
        String dateStr = elasticsearchDateConverter.format(date);
        System.out.println(dateStr);    // 2022-01-06 08:43:09
}
`

**Comment by sothawo** [comment]
You just discovered one of the reasons why `java.util.Date` should not be used for things like that (better not to use it at all, but the classes from the `java.time` package.

In the format for the converter you just use the date and time info without any timezone information, that's what a `LocalDateTime` is for: just a date with a time and no zone information attached.

A `java.util.Date` is a timestamp that contains the (milli)seconds since Unix epoch (that's January 1st 1970) in the **UTC** timezone. So when you created the `new Date()` (I think you are in a UTC+8 timezone, China, Philippines, Western Australia?) in the Date object the current timestamp in UTC time was recorded. On formatting no timezone is used, so you get this result.

**Comment by wd0401** [comment]
@sothawo tks, got it.

**Comment by wd0401** [comment]
Hi @sothawo ,I thought about this, 
 in the method (org.springframework.data.elasticsearch.core.convert.ElasticsearchDateConverter#format(java.util.Date))
```
	public String format(Date date) {

		Assert.notNull(date, "accessor must not be null");

		return dateFormatter.format(Instant.ofEpochMilli(date.getTime()));
	}
```
would we use it like this? i think it can resovle the  problem for timezone 
```
	public String format(Date date) {

		Assert.notNull(date, "accessor must not be null");

		return dateFormatter.format(LocalDateTime.ofInstant(Instant.ofEpochMilli(date.getTime()), ZoneId.systemDefault()));
	}
```
