### ISSUE TITLE
The type of AliasData filter might not be correct

### ISSUE THREAD

**Issue by oni7uka** [spring-projects/spring-data-elasticsearch#2073]
I am working on support for composable index templates. #1458 
According to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-template.html#put-index-template-api-request-body) Properties of alias:

> filter (Optional, Query DSL object) Query used to limit documents the alias can access.

But the filter property of AliasData is of type Document, it currently seems to be able to convert to and from AliasMetadata（Elasticsearch class），But it may be more reasonable to use [Query](https://github.com/spring-projects/spring-data-elasticsearch/blob/cf3e46bf68246af383393748081452172b2f4571/src/main/java/org/springframework/data/elasticsearch/core/query/Query.java#L46).

**Comment by oni7uka** [comment]
Or we should provide an override method of filter with Query parameter for AliasDataBuilder (Although there is no such class)

**Comment by sothawo** [comment]
I'll look at this later; please keep in mind, that every change / new implemenation also has to be done for the new Elasticsearch client; therefore I'd prefer to do postpone new features until at least the new client is available in the code (not as the default). I am working on this in a branch in my fork and hope to have it in the main branch soon.

**Comment by oni7uka** [comment]
@sothawo Is the new Elasticsearch client in 5.0? If so,  that the compatible spring boot version might be 3.0 which version requires Java 17，many people may not be able to upgrade Java due to business requirements, resulting in many functions that cannot be used through Spring data elasticsearch.

**Comment by sothawo** [comment]
The plan is to have the new client as an alternative in 4.4, the default being the `RestHighLevelClient` although it's deprecated now. We cannot use it as default as it's pulling in jakarta classes instead of javax. I want to have it available in 4.4 neverthelesse, otherwise that would mean working on different branches and having to do all the changes and  stuff on multiple branches.

**Comment by oni7uka** [comment]
The new elasticsearch client is implementation without server-side code, does it mean that spring data elasticsearch will also no longer use server-side code?

**Comment by sothawo** [comment]
yes, Elasticsearch created the new client to have the dependency on ES-licensed code removed from the client. The new client is Apapche2 licensed, and so are the library that it uses. The only library that will be still used the the low level `RestClient`because that already has an Apache 2 license.

This means that one of the `org.elasticsearch.*` classes that are currently used in the code can be used anymore (requests responses, converters, utilities) and need to be replaces with what's provided in the new library. And for 4.4 and probably 5.0 Spring Data Elasticsearch must be able to use either one of the clients.

**Comment by oni7uka** [comment]
Seems like a lot of work to do, there are a large number of requests and responses that need to be converted. I will commit this feature after you finish the new client branch. Please let me know if there is anything I can help with in the meantime.
