### ISSUE TITLE
RequestFactory class visibility should be public

### ISSUE THREAD

**Issue by alturkovic** [spring-projects/spring-data-elasticsearch#2096]
`AbstractElasticsearchTemplate` exposes `getRequestFactory()` method but `RequestFactory` is package-private and cannot be used.

I would like to issue the following Kotlin code:

```
template.execute { client ->
    client.deleteByQueryAsync(template.requestFactory.deleteByQueryRequest(query, clazz, index), RequestOptions.DEFAULT, myListener)
}
```

but I cannot call `deleteByQueryRequest` since it is not visible. 

Am I misusing the framework or should the visibility of `RequestFactory` be public?

**Comment by sothawo** [comment]
The ` RequestFactory` is an Spring Data Elasticsearch internal class that is not part of the API. `AbstractElasticsearchTemplate#getRequestFactory` should not have been added as a public method.

the ` execute`  method is offering the use of the ` RestHighLevelClient` but leaves it in the user's responsibility to create the requests and parse the responses.

The ` RequestFactory`  will be gone anyways after the switch to the new Elasticsearch client. So even I we were to make this class public in 4.4, it will be gone in 5.0 when the `RestHighLevelClient` - which is deprecated since Elasticsearch 7.16 and remove in Elasticsearch 8.0 - is removed.

**Comment by alturkovic** [comment]
Fair enough. I will close the issue.
