### ISSUE TITLE
The default value of refresh policy for reactive es template should be null or false

### ISSUE THREAD

**Issue by ToffeeLu** [spring-projects/spring-data-elasticsearch#2110]
It cost us 1 month to troubleshoot the issue of high indexing latency(p95 10s+) during high traffic with customized routing.
Finally we find that `RefreshPolicy` is set to `IMMEDIATE` by default, and latency becomes normal after we manually set it to `None`.

According to the [official document](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html), the default refresh behavior should be set to `false` unless you're really care about "data consistency". And only `Reactive Template` has such default value, all others are `null`.

In order to help save efforts for all users in future, I'd suggest change below two default values to `NONE` (Not sure if there's any more places):

1. https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/main/java/org/springframework/data/elasticsearch/core/ReactiveElasticsearchTemplate.java#L123
2. https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/elasticsearch/ElasticsearchDataConfiguration.java#L111

**Comment by sothawo** [comment]
You are right, but this is a breaking change in behaviour, so we can do this with the next major release - not speaking for Spring Boot, you'll have to raise an issue there.

**Comment by ToffeeLu** [comment]
@sothawo 
I've post the issue in spring boot project, https://github.com/spring-projects/spring-boot/issues/30096

Also before you guys make this breaking change, I'm thinking is it possible to add this "Configuration" information into the document? Because it's really hard to find it out. It won't cause any error, only big performance loss under high indexing traffic.

**Comment by sothawo** [comment]
I just had a deeper look into this on the Spring Data Elasticsearch side.

When not using Spring Boot, but the configuration setup like it is described in https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.clients.reactive, the refresh policy will be set to null because in `org.springframework.data.elasticsearch.config.AbstractReactiveElasticsearchConfiguration` the default value returned by `org.springframework.data.elasticsearch.config.AbstractReactiveElasticsearchConfiguration#refreshPolicy` is null. This method is used to initialize the template in this configuration approach.

Spring Boot creates the `ReactiveElasticsearchTemplate` directly with the default initialization in there and so having the refresh set to _immediately_.

The Spring Data Elasticsearch documentation does not show the direct creation of a ` ReactiveElasticsearchTemplate`, where we could put the hint on this default value.

I have no problems in changing the default value to null, as this would then be the default behaviour of Elasticsearch, but this change would affect user that have the client set up by Spring Boot and not by using the Spring Data Elasticsearch configuration class.
