### ISSUE TITLE
ContextConfiguration class is package-private in SimpleElasticsearchPersistentEntity

### ISSUE THREAD

**Issue by mlyczek** [spring-projects/spring-data-elasticsearch#2114]
In our project we are extending `SimpleElasticsearchPersistentEntity` to slightly modify the result of `getIndexCoordinates()` method to add our custom logic for automatically assigning prefix to index name. That's the only modification, we want to use the rest of `SimpleElasticsearchPersistentEntity` as it is.

But in #1788 a new inner class `ContextConfiguration` was added to `SimpleElasticsearchPersistentEntity` with package-private access, which was also added as a parameter to constructor. This means that `SimpleElasticsearchPersistentEntity` can't be extended outside of `org.springframework.data.elasticsearch.core.mapping` package despite the fact that `SimpleElasticsearchPersistentEntity` itself is `public`. That difference in access modifiers for class and its constructor parameter is a little bit misleading (and also broke our sub-class ;) )

I would like to ask if `ContextConfiguration` could be made also `public`? Looking into the code it holds only `FieldNamingStrategy` which is public and a boolean whether to save type hints into documents. Those are things that are set on mapping context and could be customised there anyway, so I think that it could be made `public` to allow extending and instantiation of `SimpleElasticsearchPersistentEntity` possible again outside of its package. Or were there some important reasons for `ContextConfiguration` being package-private?

**Comment by sothawo** [comment]
Basically I consider `SimpleElasticsearchPersistentEntity` to be an implementation detail of Spring Data Elasticsearch  which should be not used directly by an user of the library. But because of the package structure this need to be public.

The problem with having this many public classes in a library is, that when users miss some functionality, they tend to derive from and extend these classes, which in the long run makes it for the maintainers of a library harder to refactor, improve and add functionality to these classes without breaking things for people who derived from these classes.

I'd prefer if there is a problem or a missing functionality to have an issue opened where this problem can be discussed, and instead of having a local workaround it would be preferable to add missing functionality by contributing to Spring Data Elasticsearch .

**Comment by sothawo** [comment]
fixed and backported to 4.3.x branch
