### ISSUE TITLE
Support for RequestOptions in ReactiveElasticsearchClient

### ISSUE THREAD

**Issue by hraada** [spring-projects/spring-data-elasticsearch#2129]
Current synchronous `RestHighLevelClient` provides an option to specify `RequestOptions` for example in search operation. Unfortunatelly, asynchronous `ReactiveElasticsearchClient` doesn't provide such feature. In our case, it's handy to specify `filter_path` to reduce the size of response payload, but I guess there are many more use cases.

Current synchronous client example wtih request options with custom parameter:
```java
RestHighLevelClient syncClient = ....
var options = RequestOptions.DEFAULT.toBuilder().addParameter("filter_path", "took,aggregations.*").build();
var response = syncClient.search(request, options)
```
Example of feature usage in reactive client example (currently missing):
```java
ReactiveElasticsearchClient reactiveClient = ....
var options = RequestOptions.DEFAULT.toBuilder().addParameter("filter_path", "took,aggregations.*").build();
var response = reactiveClient.searchForResponse(request, options)
```

**Comment by sothawo** [comment]
The `ReactiveElasticsearchClient` is not a reactive counterpart of the `RestHighLevelClient` and so it's methods and signatures do not match the ones of the Elasticsearch class, so that's the main reason for not having this in the methods up to now.

What about adding? We are currently integrating the new Elasticsearch client into Spring Data Elasticsearch as the `RestHighLevelClient` does not exist anymore in Elasticsearch 8. The now existing `ReactiveElasticsearchClient` will then be replaced by a new version which will use the async methods of the `ElasticsearchClient`. So setting these options in the future will be the same for imperative and reactive code, as it seems these are not set on the individual methods but when creating the `ElasticsearchClient` instance.

So for me it does not make sense to add this to the current implementation.

**Comment by hraada** [comment]
Thanks for answer, it makes sense (not to add it) with such future plans. I will find a workaround until new Elasticsearch client will be integrated.
