### ISSUE TITLE
QueryParserUtil always escape " to \", there seems no way to transfer "\"search some text\"" to queryStringQueryBuilder

### ISSUE THREAD

**Issue by 564155611** [spring-projects/spring-data-elasticsearch#2356]
##### for example: findByFileNameOrFolderName(String fileName,String folderName):  
```  
i need to build QueryStringQueryBuilder like this: new QueryStringQueryBuilder("\"abc ef\""),   
but with Spring data elasticsearch, the result will become new QueryStringQueryBuilder("\\\"abc ef\\\"").  
```   
is there any way to tell spring data elasticsearch: don't escape search text?  
my spring data elasticsearch version is 4.3.0

**Comment by sothawo** [comment]
It's not clear what your problem is and how that relates to Spring Data Elasticsearch.

`QueryStringQueryBuilder` is a class from the Elasticsearch libraries and the `QueryParser` stuff is Lucene code used by the Elasticsearch code.

And how does this relate to a method `findByFileNameOrFolderName`?

**Comment by 564155611** [comment]
**This is part of the source code in CriteriaQueryProcessor.java**:
![image](https://user-images.githubusercontent.com/73692902/202069318-286104c1-3ec9-40ec-9db2-ca446fa93666.png)
```  
**And you can see that:**  
- when entry.getValue() gets the value of "abc ef", the search text will become "abc ef"  
 - when entry.getValue() gets the value of  
"\"abc ef\"", the searchText will become "\\\"abc ef\\\"".  
  
**the problem is :**  
The question is in what case can I make this searchText become "\"abc ef\""  
```

**Comment by 564155611** [comment]
with criteria entry there seems no way to build QueryStringQueryBuilder with value: "\"abc ef\""

**Comment by sothawo** [comment]
The code you show (is from an old version anyway, but escaping is still done) is used to escape a string passed in as a **value** for a criteria entry. Values must be escaped.

If you have a value `\"abc ef\"` that means that the value already contains a blackslash, then a quote, then text and so on. Backslashes and quotes must be escaped in order to be sent.

Please provide a concrete, reproducable and runnable example of code, how you build the query and with what values to use.

**Comment by 564155611** [comment]
``` java
//build query by criteria
        ApplicationContext applicationContext = ContextUtils.getApplicationContext();
        ElasticsearchOperations elasticsearchOperations = applicationContext.getBean(PostProcessElasticsearchOperations.class);
        ElasticsearchConverter elasticsearchConverter = elasticsearchOperations.getElasticsearchConverter();
        PartTree tree = new PartTree("findByColor", Product.class);
        ElasticsearchQueryCreator queryCreator = new ElasticsearchQueryCreator(tree, elasticsearchConverter.getMappingContext());
        String param = "red blue \"quick brown\"";
        CriteriaQuery query = EsUtil.createCriteria(queryCreator, tree, param);
        SearchHits<Product> product = elasticsearchOperations.search(query, Product.class, IndexCoordinates.of("product"));
        // TODO:   
        
        //native query
        QueryStringQueryBuilder queryBuilder = new QueryStringQueryBuilder(param).field("color");
        SearchRequest searchRequest = new SearchRequest("product");
        searchRequest.source().query(queryBuilder);
        client.search(searchRequest, RequestOptions.DEFAULT);
        // TODO:
```

**Comment by 564155611** [comment]
for example i want to parse query string as three different terms:
1.red
2.blue
3.quick brown
``` 
i need to build a query: new QueryStringQueryBuilder("red blue \"quick brown\""), but with criteria query the result will become new QueryStringQueryBuilder("red blue \\\"quick brown\\\"")
```

**Comment by sothawo** [comment]
These lines of code are not a reproducible or runnable example. I don't know why you are creating a `PartTree` or an 
`ElasticsearchQueryCreator` by yourself. I'll try to show what I understand is the problem to solve with Spring Data 
Elasticsearch.

There is an entity called `Product` that has a property called `color`. This might be mapped to a type of either 
'keyword' or 'text', the difference is the created query for this. You want to search for entities where the `color` 
property matches one of several values.

In order to query this, the easiest way is to define a repository:

```java
public interface ProductRepository extends ElasticsearchRepository<Product, String> {
	SearchHits<Product> findByColorIn(List<String> colors);
}

```

You can then use this repository:
```java
repository.findByColorIn(List.of("red", "blue", "quick brown"));
```

Or you use a `CriteriaQuery` with an `ElastcisearchOperations` implementation:
```java
operations.search(CriteriaQuery.builder(Criteria.where("color").in("red", "blue", "quick brown")).build(), Product.class);
```

This is what is provided and supported by Spring Data Elasticsearch.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by 564155611** [comment]
Using findByColorIn, it is possible to solve the problem of "quotation marks being escaped". The source code is marked as follows:
![image](https://user-images.githubusercontent.com/73692902/203908761-dea07470-fff8-48ff-b5b2-d2c12945d912.png)
Step 1: It first appends the quotation marks
② Step 2: QueryParserUtil.escape

**Comment by 564155611** [comment]
But I need to let elasticsearch analyze the string itself and get the corresponding terms.
Since the user enters the string in the input box, I have no way of knowing how many terms it will eventually be split into.

**Comment by 564155611** [comment]
Although I can get the corresponding terms through a POST _analyze request, this means I need to do two additional things:
① get the search_analyzer corresponding to the Color field
② use the search_analyzer obtained in the previous step to perform a POST _analyze request

**Comment by sothawo** [comment]
Wether the passed in parameter is tokenized and analysed by Elasticsearch depends on the mapping of the field. If it is mapped as `text`, it will be analyzed, if it is a `keyword`, then it's taken as it is.

If the query that is produced by Spring Data Elasticsearch either from a repository method or when using a `CriteriaQuery` is not what you need, then you'll have to build the query by using the functionality from the Elasticsearch libraries and pass that into a `NativeQuery` (current version 5.0 of Spring Data Elasticsearch) or `NativeSearchQuery` (previous version 4.4)
