### ISSUE TITLE
@EnableReactiveElasticsearchAuditing not work

### ISSUE THREAD

**Issue by SilenceRainly** [spring-projects/spring-data-elasticsearch#2408]
springboot3 
![image](https://user-images.githubusercontent.com/37230683/209895663-e97c07b6-34eb-4155-95f6-b8bc32d7ad52.png)
![image](https://user-images.githubusercontent.com/37230683/209895700-873dc660-5db0-455c-9f3d-a8e4224227c7.png)
![image](https://user-images.githubusercontent.com/37230683/209895714-4afdbb95-1945-484a-99a2-8fb1628be8e9.png)

**Comment by sothawo** [comment]
Please refrain from posting images instead of code.

This is not a problem of Spring Data Elasticsearch but rather of Spring Boot which should create a bean named "elasticsearchMappingContext". 

If you configure Spring Data Elasticsearch explicitly like [documented here](https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.clients.reactiverestclient) you do not have this problem as in this case the created bean has the correct name.

You probably should open an issue with [Spring Boot](https://github.com/spring-projects/spring-boot/issues).
