### ISSUE TITLE
The number of pages cannot be set by scrolling, and it is fixed to 500 pages, which is not conducive to data paging.

### ISSUE THREAD

**Issue by lzzkey** [spring-projects/spring-data-elasticsearch#2495]
![image](https://user-images.githubusercontent.com/56814753/225868552-26acd7d4-3eee-435b-85b7-5820c61faf7b.png)

The version is version 5.0.4. If the number of pages is set at the beginning of turning the page, the final code here will not take effect, because it is fixed to 500 records one page, but as a user, it needs a more flexible paging method, so I hope to modify this part of the code.

**Comment by sothawo** [comment]
There is no version 5.0.4 of Spring Data Elasticsearch. The latest patch version for the 5.0 branch is 5.0.3, released on 03.03.2023.

The code you show in that image for setting the batch size is from before 7.12.2022 when this was changed by #2392.
But the reactive code doesn't now even use this scroll search any longer, since #2393 (12.12.2022) it uses the point-in-time API.

So you are looking at code that is not up to date.
