### ISSUE TITLE
how to search es without Document-Entity

### ISSUE THREAD

**Issue by wang-xiaowu** [spring-projects/spring-data-elasticsearch#2503]
spring-data-elasticsearch: 5.0.3
springboot: 3.0.4

i need to search data from the log-index in es
and the index used the ilm_policy
it will delete the index which is 15 days before

so i am finding a api like
```java
operations.search(query, IndexCoordinates.of(indexNameProvider.indexName()));
```
but all apis seem like entity param is necessary
```java
operations.search(query, SampleEntity.class, IndexCoordinates.of(indexNameProvider.indexName()));
```

**Comment by sothawo** [comment]
That's the point of all Spring Data implementations, not only Spring Data Elasticsearch: Mapping entities to store specific representations and be able to save and retrieve them.

If you do not use Spring Data Elasticsearch to store data in the index, you need to define an entity class that models the data you want to retrieve from the index (id property, other properties like timestamps, text fields). Set the types and names with the `@Field` annotation on your entity start querying your data.

In what format should the found data be returned otherwise?

**Comment by wang-xiaowu** [comment]
you are right.
but is there any method can resolve my question?
now the situation is my index maybe not exitsts after 15 days,
so how can i configure the propertie `indexName`?
```java
@Document(indexName = "?", createIndex = false)
```

**Comment by wang-xiaowu** [comment]
i will try spEL to test it later

**Comment by sothawo** [comment]
SpEL is one possibility, a wildcard name like "logs-*" would be another one. The search will return a `SearchHit<T>` and this contains the actual name where to entity was found, in case you need that information.

**Comment by wang-xiaowu** [comment]
> SpEL is one possibility, a wildcard name like "logs-*" would be another one. The search will return a `SearchHit<T>` and this contains the actual name where to entity was found, in case you need that information.

thanks, after using `log-*` it's worked.
but i have one question,
now i just wanna aggregate the data, 
so the entity which i defined seems like meaningless

like

![image](https://user-images.githubusercontent.com/44340137/226865440-e7a3c3e9-261a-4946-ab15-e29a031cc277.png)
![image](https://user-images.githubusercontent.com/44340137/226865617-d39782ec-eada-4dac-9efa-fed583c7a137.png)

plus: do we have a easy method to use aggregation, it's too hard to get the data

**Comment by sothawo** [comment]
you need the entity class anyway.
