### ISSUE TITLE
DeleteByQuery implementation is confusing

### ISSUE THREAD

**Issue by axelczk** [spring-projects/spring-data-elasticsearch#2864]
In Elastic REST API the operations _update_by_query and _delete_by_query are very similar:
They both accept a query and they have similar properties. 

But in the current implementation of spring, we can't pass parameter to the delete method. The only things we can pass is the query and the index coordinates. 

We should be able to pass parameter like Slice, requests_per_second, conflicts, etc like the update query. 

My current problem with this is we tried to migrate from the Spring Data ES 4 to Spring Data ES 5 but our current E2E tests failed due to a lot of conflict error with the new delete by query implementation due to a difference in parameter between the 4.X and the 5.X. 

In the previous version, the delete by query had slice=1, requests_per_second=-1,wait_for_completion=true and now it's not the case anymore. 

Is there any explanation why the delete doesn't allow setting these parameter or allow more custom configuration and possibly introduce a retryOnConflict parameter ? 

Maybe it's us who are doing something wrong with our delete but in the current state, we can't migrate due to a high number of conflict.

**Comment by sothawo** [comment]
Half of your post is a verbatim copy of #2544 (even copied the title) please read the answer to that post.

The `ElasticsearchOperations.delete(...)` methods taking a `Query` objects were introduced in 4.1 and have not changed since then. What has changed is the used client from Elasticsearch. If then the request that is sent to Elasticsearch has changed, then the client implementation has a different behaviour since Elasticsearch 8, that is not a Spring Data Elasticsearch thing.

It currently is not - and never was - possible to set `slices` etc on a delete. To add this, we need to introduce a new `DeleteQuery` class that can hold these parameters as we cannot extend the existing `Query` with that. I created #2865 for that.

**Comment by axelczk** [comment]
That was the point because the answer was correct for his question but not factually valid regarding the ES API. 

Indeed no updateQuery is needed for a delete operation, but both API: delete_by_query and update_by_query provide the same parameters, and the current version of the ElasticsearchOperations.delete is quite outdated and is the single query that did not change with the new major version. All others query have been revamped with new object and builder that are to be honest easier to use. 

Do you need help to implement https://github.com/spring-projects/spring-data-elasticsearch/issues/2865 ?

This issue is quite important for our project to be able to easily control the behavior of our delete and avoid any conflict exception on ES side.
