### ISSUE TITLE
How to limit data per page?

### ISSUE THREAD

**Issue by eacdy** [spring-projects/spring-data-elasticsearch#2877]
We use ElasticsearchRestTemplate to search data in ES. Here goes an example:
```java
SearchQuery query = new NativeSearchQueryBuilder()
                .withQuery(boolQueryBuilder)
                .withPageable(PageRequest.of(0, 5000))
                .build();
elasticsearchRestTemplate.queryForPage(query, TicketQuery.class);
```
I Want to limit page size too avoid some problem, such as OOM. Do we have any way to validate Whether it is too big?

**Comment by sothawo** [comment]
> Do we have any way to validate Whether it is too big?

No. Because the page size not only depends on the number of documents returned but also on the size of the documents. If each document has a size of 100 bytes you'd get almost half a megabyte back. If you documents are larger, for example 20kB, a page size of 5000 would return a response with a size of 100MB
