### ISSUE TITLE
There is a conflict between the package types of the two versions.

### ISSUE THREAD

**Issue by aiYunS-love** [spring-projects/spring-data-elasticsearch#2956]
<dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-elasticsearch</artifactId>
            <version>5.3.2</version>
        </dependency>
<dependency>
            <groupId>co.elastic.clients</groupId>
            <artifactId>elasticsearch-java</artifactId>
            <version>7.17.23</version>
</dependency>
<img width="838" alt="65A64D319DE99AB65FD6B36511BD7636" src="https://github.com/user-attachments/assets/7a67106d-3882-4dc7-9c1a-3d0f9394ea34">
<img width="660" alt="987FB4D647E725DF226AAA2DBD9B7A3A" src="https://github.com/user-attachments/assets/35e14cef-102d-4711-bc02-d90989977b5b">

**Comment by sothawo** [comment]
Spring Data Elasticsearch since version 5.3.2 is built against Elasticsearch 8.13.4. The parameter of these type obviously changed in the Elasticsearch client since version 7.17.23, that's nothing where Spring Data Elasticsearch could do anything. Some of these parameters in the Elasticsearch client library even changed with patch level changes.

The conflict you get is because you do not use the Elasticsearch library that Spring Data Elasticsearch is built against. You should use the Elasticsearch client libs in the correct versions, as defined by the Spring Data Elasticsearch pom and documented in the release notes (https://docs.spring.io/spring-data/elasticsearch/reference/elasticsearch/versions.html it seems I forgot to update this with 5.3.2)
