### ISSUE TITLE
dynamic indexname

### ISSUE THREAD

**Issue by oalam** [spring-projects/spring-data-elasticsearch#45]
I would like to specify to which index to store my entities at runtime. For now I need to use  introspection to do so.

**Comment by sothawo** [comment]
This issue surfaced again after switching from Jira issues to GitHub where it obviously was created a long time ago.

As example of how dynamic index names can be used since Spring Data Elasticsearch 4 check https://www.sothawo.com/2020/08/use-an-index-name-defined-by-the-entity-to-store-data-in-spring-data-elasticsearch-4-0/ and https://www.sothawo.com/2020/07/how-to-provide-a-dynamic-index-name-in-spring-data-elasticsearch-using-spel/
