### ISSUE TITLE
Inner Hits support [DATAES-263]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#839]
**[FRANCK LEFEBURE](https://jira.spring.io/secure/ViewProfile.jspa?name=franck.lefebure@gmail.com)** opened **[DATAES-263](https://jira.spring.io/browse/DATAES-263?redirect=false)** and commented

ElasticSearch allows to fetch nested objects or children/parent objects that are targeted in the query (with a nested, has_child or has_parent filter)

If the filter shows a "innerhits" modifier, then the targeted objects figure in the response as a json "innerHits" structure eg

"inner_hits": {"activities": {"hits":{  "total": 2,...

The purpose of this ticket is to have the possibility to map the innerhits results on a Spring Data entity property.

I have a branch, that I'm going to propose as a pull-request, that implements this feature

Nested object has to be annotated with a new annotation eg :

`@JsonIgnore`
`@InnerHits`(path = "activities")
private Set\<Activity> activities;

The param "path" must match the path of the nested object in the query, or the parent/child type.
As a result, the collection or the relation is populated...

---

**Referenced from:** pull request https://github.com/spring-projects/spring-data-elasticsearch/pull/473

2 votes, 4 watchers

**Comment by gquintillan** [comment]
Hello, 

Is there any example about how to achieve the mapping of the inner hit?

- I have defined a structure similar to this:

```
@Document(indexName = "myDocument")
public class MyDocument {

    @Field(type = FieldType.Object)
    private MySubDocument subDocument;

} 

public class SubDocument {

    @Field(type = FieldType.Nested)
    private List<MyNestedDocument> nestedDocuments;

} 

```

- Using [NativeQuery.builder()](https://docs.spring.io/spring-data/elasticsearch/docs/5.1.3/api/org/springframework/data/elasticsearch/client/elc/NativeQuery.html#builder()) I defined a **nested** query with `innerHits`.  
- I set the [path](https://artifacts.elastic.co/javadoc/co/elastic/clients/elasticsearch-java/8.7.1/co/elastic/clients/elasticsearch/_types/query_dsl/NestedQuery.Builder.html#path(java.lang.String)) of the nested query to "subDocument.nestedDocuments".
- The query is executed with elasticsearchOperations.search(query, MyDocument.class)
- I can access one of the inner hits like this: 
```SearchHits<MyDocument> hits = elasticsearchOperations.search(query, MyDocument.class);

SearchDocumentAdapter documentAdapter = hits.getSearchHits().get(0).getInnerHits("subDocument.nestedDocuments").getSearchHits().get(0);
```
The problem is that I expected to get an instance of `MyNestedDocument` but I'm getting an instance of [SearchDocumentAdapter](https://github.com/spring-projects/spring-data-elasticsearch/blob/3f085b267585a4f1edcb24efd648c8bc52f2703c/src/main/java/org/springframework/data/elasticsearch/core/document/SearchDocumentAdapter.java) instead. Is there a way to achieve it?

I debugged it and I think the problem is here:

https://github.com/spring-projects/spring-data-elasticsearch/blob/3f085b267585a4f1edcb24efd648c8bc52f2703c/src/main/java/org/springframework/data/elasticsearch/core/SearchHitMapping.java#L208

If I understood correctly, It tries to perform the mapping using `MyDocument.class `instead of  `MyNestedDocument.class` and that's why it uses the default [SearchDocumentAdapter](https://github.com/spring-projects/spring-data-elasticsearch/blob/3f085b267585a4f1edcb24efd648c8bc52f2703c/src/main/java/org/springframework/data/elasticsearch/core/document/SearchDocumentAdapter.java) in the end.

**Comment by sothawo** [comment]
The API doc for `SearchHit.getInnerHits()`:
```
	/**
	 * returns the {@link SearchHits} for the inner hits with the given name. If the inner hits could be mapped to a
	 * nested entity class, the returned data will be of this type, otherwise
	 * {{@link org.springframework.data.elasticsearch.core.document.SearchDocument}} instances are returned in this
	 * {@link SearchHits} object.
	 *
	 * @param name the inner hits name
	 * @return {@link SearchHits} if available, otherwise {@literal null}
	 */
```

So it seems, your `MyNestedDocument` is not known to the MappingConverter. What do you get back when you do a normal search? Are then the `subdocument.nestedDocument` values correct?

If you check the tests at you see that we there have a three-level object structure as well, and there the mapping works.

https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/test/java/org/springframework/data/elasticsearch/core/InnerHitsIntegrationTests.java

**Comment by gquintillan** [comment]
>  What do you get back when you do a normal search? Are then the subdocument.nestedDocument values correct?
I can follow the whole structure, from the top to the bottom, everything is mapped correctly.

I'm comparing with the example of the Unit Test and I cannot see what I'm doing wrong, it is very similar.

**Comment by gquintillan** [comment]
The main difference I see is that in our case, the first nested relationship is a `FieldType.Object` and it is not a list, just 1 instance.

Taking the `city (@Document) -> houses (FieldType.Nested) -> inhabitants (FieldType.Nested)` as example we would have then:
`city (@Document) -> house (FieldType.Object) -> inhabitants (FieldType.Nested)`.

The workaround we found is to declare House as a `@Document` and then we do the mapping of inhabitants as a relative path to the root, for instance:

```
@Document(indexName = "#{@indexNameProvider.indexName()}")
class House {
		@Field(name = "hou-se.in-habi-tants", type = FieldType.Nested) private List<Inhabitant> inhabitants = new ArrayList<>();
```

And then we execute the search query passing `House.class` (instead of `City.class`) :
`elasticsearchOperations.search(query, House.class);`

That way we get the Inner Hits mapping (of Inhabitant in this example) properly done.
